"""rm name

Revision ID: 54e01fc68bc9
Revises: c3fb1dd20729
Create Date: 2019-11-01 17:42:38.229042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54e01fc68bc9'
down_revision = 'c3fb1dd20729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ranking_manage_name', table_name='ranking_manage')
    op.drop_column('ranking_manage', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranking_manage', sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=16), nullable=True))
    op.create_index('ix_ranking_manage_name', 'ranking_manage', ['name'], unique=False)
    # ### end Alembic commands ###
