"""add rankong

Revision ID: c3fb1dd20729
Revises: 
Create Date: 2019-11-01 17:39:41.884570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fb1dd20729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_manage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('click_num', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_manage_click_num'), 'ranking_manage', ['click_num'], unique=False)
    op.create_index(op.f('ix_ranking_manage_name'), 'ranking_manage', ['name'], unique=False)
    op.create_index(op.f('ix_ranking_manage_title'), 'ranking_manage', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ranking_manage_title'), table_name='ranking_manage')
    op.drop_index(op.f('ix_ranking_manage_name'), table_name='ranking_manage')
    op.drop_index(op.f('ix_ranking_manage_click_num'), table_name='ranking_manage')
    op.drop_table('ranking_manage')
    # ### end Alembic commands ###
